### ISSUE TITLE
Both of demos crashed while unloading on VBIDE

### ISSUE THREAD

**Issue by Jonney3099** [tannerhelland/pd2D#1]
Private Sub Form_Unload(Cancel As Integer)

```
'If an animated demo is still running, make sure to turn it off!
tmrSample.Enabled = False

'Before we exit, release the rendering backend we started inside Form_Load
Drawing2D.StopRenderingEngine P2_DefaultBackend
```

End Sub

GDI+ shut down already but pd2DDIB and pd2DSurface still live then crashed while those classes terminating.

**Comment by tannerhelland** [comment]
Thank you for reporting this, @Jonney3099.  I appreciate your help!
